name: aparmar_cv_proj
channels:
  - anaconda
  - intel
  - defaults
dependencies:
  - blas=1.0
  - ca-certificates=2020.1.1
  - certifi=2020.4.5.1
  - cycler=0.10.0
  - freetype=2.9.1
  - intel-openmp=2020.0
  - kiwisolver=1.1.0
  - libcxx=4.0.1
  - libcxxabi=4.0.1
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgfortran=3.0.1
  - libpng=1.6.37
  - matplotlib=3.1.1
  - mkl=2019.5
  - mkl-service=2.3.0
  - mkl_fft=1.0.15
  - mkl_random=1.1.0
  - ncurses=6.2
  - numpy=1.17.3
  - numpy-base=1.17.3
  - openssl=1.1.1
  - pip=20.0.2
  - pyparsing=2.4.6
  - python=3.6.7
  - python-dateutil=2.8.1
  - pytz=2019.3
  - readline=7.0
  - scipy=1.2.1
  - setuptools=46.1.3
  - six=1.14.0
  - sqlite=3.31.1
  - tk=8.6.8
  - tornado=6.0.4
  - wheel=0.34.2
  - xz=5.2.4
  - zlib=1.2.11
  - pip:
    - joblib==0.14.1
    - opencv-python==3.4.3.18
    - scikit-learn==0.22

