name: parmar_cv_proj
channels:
  - intel
  - defaults
dependencies:
  - bzip2=1.0.8
  - certifi=2019.11.28
  - cycler=0.10.0
  - freetype=2.10.1
  - icc_rt=2020.1
  - intel-openmp=2020.1
  - intelpython=2020.1
  - kiwisolver=1.1.0
  - libcxx=4.0.1
  - libcxxabi=4.0.1
  - libffi=3.3
  - libpng=1.6.37
  - matplotlib=3.1.1
  - mkl=2020.1
  - mkl-service=2.3.0
  - mkl_fft=1.1.0
  - mkl_random=1.1.0
  - numpy-base=1.17.5
  - openssl=1.1.1d
  - pip=19.3.1
  - pyparsing=2.4.5
  - python=3.7.7
  - python-dateutil=2.8.1
  - pytz=2019.3
  - setuptools=45.2.0
  - six=1.13.0
  - sqlite=3.30.1
  - tbb=2020.2
  - tbb4py=2020.2
  - tcl=8.6.9
  - tk=8.6.9
  - wheel=0.33.6
  - xz=5.2.4
  - zlib=1.2.11.1
  - pip:
    - joblib==0.14.1
    - numpy==1.18.3
    - opencv-python==3.4.3.18
    - scikit-learn==0.22.2
    - scipy==1.4.1

